//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDoldur.WebServiceDoldurSoap")]
    public interface WebServiceDoldurSoap {
        
        // CODEGEN: Generating message contract since element name DoldurSehirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoldurSehir", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse DoldurSehir(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoldurSehir", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse> DoldurSehirAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoldurSehirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoldurSehir", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequestBody Body;
        
        public DoldurSehirRequest() {
        }
        
        public DoldurSehirRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DoldurSehirRequestBody {
        
        public DoldurSehirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoldurSehirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoldurSehirResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponseBody Body;
        
        public DoldurSehirResponse() {
        }
        
        public DoldurSehirResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoldurSehirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoldurSehirResult;
        
        public DoldurSehirResponseBody() {
        }
        
        public DoldurSehirResponseBody(string DoldurSehirResult) {
            this.DoldurSehirResult = DoldurSehirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDoldurSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDoldurSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap {
        
        public WebServiceDoldurSoapClient() {
        }
        
        public WebServiceDoldurSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDoldurSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDoldurSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDoldurSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap.DoldurSehir(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest request) {
            return base.Channel.DoldurSehir(request);
        }
        
        public string DoldurSehir() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap)(this)).DoldurSehir(inValue);
            return retVal.Body.DoldurSehirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap.DoldurSehirAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest request) {
            return base.Channel.DoldurSehirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirResponse> DoldurSehirAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.DoldurSehirRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoldur.WebServiceDoldurSoap)(this)).DoldurSehirAsync(inValue);
        }
    }
}
