//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktor()
        {
            this.Mesais = new HashSet<Mesai>();
            this.Randevus = new HashSet<Randevu>();
            this.Saats = new HashSet<Saat>();
        }
    
        public int doktorID { get; set; }
        public int klinikID { get; set; }
        public string doktorEmail { get; set; }
        public string doktorAd { get; set; }
        public string doktorSoyad { get; set; }
        public string doktorTc { get; set; }
        public string doktorTel { get; set; }
        public string doktorCinsiyet { get; set; }
        public string doktorSifre { get; set; }
    
        public virtual Klinik Klinik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesai> Mesais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saat> Saats { get; set; }
    }
}
