//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saat
    {
        public int saatID { get; set; }
        public int doktorID { get; set; }
        public System.TimeSpan saatBaslama { get; set; }
        public System.TimeSpan saatBitis { get; set; }
        public System.TimeSpan saatPeriyot { get; set; }
        public System.TimeSpan saatOgleBaslama { get; set; }
        public System.TimeSpan saatOgleBitis { get; set; }
    
        public virtual Doktor Doktor { get; set; }
    }
}
