//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRandevuDetay
    {
        public int uyeID { get; set; }
        public string uyeAd { get; set; }
        public int doktorID { get; set; }
        public string doktorAd { get; set; }
        public int klinikID { get; set; }
        public string klinikAd { get; set; }
        public int hastaneID { get; set; }
        public string hastaneAd { get; set; }
        public int ilceID { get; set; }
        public string ilceAd { get; set; }
        public int sehirID { get; set; }
        public string sehirAd { get; set; }
        public int randevuID { get; set; }
        public System.DateTime randevuTarihSaat { get; set; }
    }
}
