//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUye.WebServiceUyeGirisSoap")]
    public interface WebServiceUyeGirisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        bool Guncelle(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GuncelleAsync(int uyeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        int Ekle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EkleAsync();
        
        // CODEGEN: Generating message contract since element name uyeTC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UyeKontrol", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse UyeKontrol(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UyeKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse> UyeKontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UyeKontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UyeKontrol", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequestBody Body;
        
        public UyeKontrolRequest() {
        }
        
        public UyeKontrolRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UyeKontrolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uyeTC;
        
        public UyeKontrolRequestBody() {
        }
        
        public UyeKontrolRequestBody(string uyeTC) {
            this.uyeTC = uyeTC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UyeKontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UyeKontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponseBody Body;
        
        public UyeKontrolResponse() {
        }
        
        public UyeKontrolResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UyeKontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UyeKontrolResult;
        
        public UyeKontrolResponseBody() {
        }
        
        public UyeKontrolResponseBody(string UyeKontrolResult) {
            this.UyeKontrolResult = UyeKontrolResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUyeGirisSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUyeGirisSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap {
        
        public WebServiceUyeGirisSoapClient() {
        }
        
        public WebServiceUyeGirisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUyeGirisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUyeGirisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUyeGirisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Guncelle(int uyeID) {
            return base.Channel.Guncelle(uyeID);
        }
        
        public System.Threading.Tasks.Task<bool> GuncelleAsync(int uyeID) {
            return base.Channel.GuncelleAsync(uyeID);
        }
        
        public int Ekle() {
            return base.Channel.Ekle();
        }
        
        public System.Threading.Tasks.Task<int> EkleAsync() {
            return base.Channel.EkleAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap.UyeKontrol(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest request) {
            return base.Channel.UyeKontrol(request);
        }
        
        public string UyeKontrol(string uyeTC) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequestBody();
            inValue.Body.uyeTC = uyeTC;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap)(this)).UyeKontrol(inValue);
            return retVal.Body.UyeKontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap.UyeKontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest request) {
            return base.Channel.UyeKontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolResponse> UyeKontrolAsync(string uyeTC) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.UyeKontrolRequestBody();
            inValue.Body.uyeTC = uyeTC;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceUye.WebServiceUyeGirisSoap)(this)).UyeKontrolAsync(inValue);
        }
    }
}
