//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSaat.WebServiceSaatSoap")]
    public interface WebServiceSaatSoap {
        
        // CODEGEN: Generating message contract since element name EkleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse Ekle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse> EkleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest request);
        
        // CODEGEN: Generating message contract since element name GuncelleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse Guncelle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse> GuncelleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        int Kontrol(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<int> KontrolAsync(int doktorID);
        
        // CODEGEN: Generating message contract since element name DoldurResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doldur", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse Doldur(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doldur", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse> DoldurAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ekle", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequestBody Body;
        
        public EkleRequest() {
        }
        
        public EkleRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        public EkleRequestBody() {
        }
        
        public EkleRequestBody(int doktorID) {
            this.doktorID = doktorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponseBody Body;
        
        public EkleResponse() {
        }
        
        public EkleResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EkleResult;
        
        public EkleResponseBody() {
        }
        
        public EkleResponseBody(string EkleResult) {
            this.EkleResult = EkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Guncelle", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequestBody Body;
        
        public GuncelleRequest() {
        }
        
        public GuncelleRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        public GuncelleRequestBody() {
        }
        
        public GuncelleRequestBody(int doktorID) {
            this.doktorID = doktorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponseBody Body;
        
        public GuncelleResponse() {
        }
        
        public GuncelleResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuncelleResult;
        
        public GuncelleResponseBody() {
        }
        
        public GuncelleResponseBody(string GuncelleResult) {
            this.GuncelleResult = GuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoldurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doldur", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequestBody Body;
        
        public DoldurRequest() {
        }
        
        public DoldurRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoldurRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        public DoldurRequestBody() {
        }
        
        public DoldurRequestBody(int doktorID) {
            this.doktorID = doktorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoldurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoldurResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponseBody Body;
        
        public DoldurResponse() {
        }
        
        public DoldurResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoldurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoldurResult;
        
        public DoldurResponseBody() {
        }
        
        public DoldurResponseBody(string DoldurResult) {
            this.DoldurResult = DoldurResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSaatSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSaatSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap {
        
        public WebServiceSaatSoapClient() {
        }
        
        public WebServiceSaatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSaatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSaatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSaatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.Ekle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest request) {
            return base.Channel.Ekle(request);
        }
        
        public string Ekle(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequestBody();
            inValue.Body.doktorID = doktorID;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).Ekle(inValue);
            return retVal.Body.EkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.EkleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest request) {
            return base.Channel.EkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleResponse> EkleAsync(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.EkleRequestBody();
            inValue.Body.doktorID = doktorID;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).EkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.Guncelle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest request) {
            return base.Channel.Guncelle(request);
        }
        
        public string Guncelle(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequestBody();
            inValue.Body.doktorID = doktorID;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).Guncelle(inValue);
            return retVal.Body.GuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.GuncelleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest request) {
            return base.Channel.GuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleResponse> GuncelleAsync(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.GuncelleRequestBody();
            inValue.Body.doktorID = doktorID;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).GuncelleAsync(inValue);
        }
        
        public int Kontrol(int doktorID) {
            return base.Channel.Kontrol(doktorID);
        }
        
        public System.Threading.Tasks.Task<int> KontrolAsync(int doktorID) {
            return base.Channel.KontrolAsync(doktorID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.Doldur(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest request) {
            return base.Channel.Doldur(request);
        }
        
        public string Doldur(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequestBody();
            inValue.Body.doktorID = doktorID;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).Doldur(inValue);
            return retVal.Body.DoldurResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap.DoldurAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest request) {
            return base.Channel.DoldurAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurResponse> DoldurAsync(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.DoldurRequestBody();
            inValue.Body.doktorID = doktorID;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceSaat.WebServiceSaatSoap)(this)).DoldurAsync(inValue);
        }
    }
}
