//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMesai.WebServiceMesaiSoap")]
    public interface WebServiceMesaiSoap {
        
        // CODEGEN: Generating message contract since element name mesaiSaat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse Ekle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse> EkleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest request);
        
        // CODEGEN: Generating message contract since element name mesaiSaat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse Guncelle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse> GuncelleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name GetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getir", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse Getir(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getir", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse> GetirAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        int Kontrol(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<int> KontrolAsync(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        void Sil(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        System.Threading.Tasks.Task SilAsync(int doktorID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ekle", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequestBody Body;
        
        public EkleRequest() {
        }
        
        public EkleRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat;
        
        public EkleRequestBody() {
        }
        
        public EkleRequestBody(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            this.doktorID = doktorID;
            this.mesaiSaat = mesaiSaat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponseBody Body;
        
        public EkleResponse() {
        }
        
        public EkleResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EkleResponseBody {
        
        public EkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Guncelle", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequestBody Body;
        
        public GuncelleRequest() {
        }
        
        public GuncelleRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat;
        
        public GuncelleRequestBody() {
        }
        
        public GuncelleRequestBody(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            this.doktorID = doktorID;
            this.mesaiSaat = mesaiSaat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponseBody Body;
        
        public GuncelleResponse() {
        }
        
        public GuncelleResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GuncelleResponseBody {
        
        public GuncelleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getir", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequestBody Body;
        
        public GetirRequest() {
        }
        
        public GetirRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        public GetirRequestBody() {
        }
        
        public GetirRequestBody(int doktorID) {
            this.doktorID = doktorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponseBody Body;
        
        public GetirResponse() {
        }
        
        public GetirResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetirResult;
        
        public GetirResponseBody() {
        }
        
        public GetirResponseBody(string GetirResult) {
            this.GetirResult = GetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMesaiSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMesaiSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap {
        
        public WebServiceMesaiSoapClient() {
        }
        
        public WebServiceMesaiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMesaiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMesaiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMesaiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.Ekle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest request) {
            return base.Channel.Ekle(request);
        }
        
        public void Ekle(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.mesaiSaat = mesaiSaat;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).Ekle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.EkleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest request) {
            return base.Channel.EkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleResponse> EkleAsync(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.EkleRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.mesaiSaat = mesaiSaat;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).EkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.Guncelle(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest request) {
            return base.Channel.Guncelle(request);
        }
        
        public void Guncelle(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.mesaiSaat = mesaiSaat;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).Guncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.GuncelleAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest request) {
            return base.Channel.GuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleResponse> GuncelleAsync(int doktorID, _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.TimeSpan mesaiSaat) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GuncelleRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.mesaiSaat = mesaiSaat;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).GuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.Getir(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest request) {
            return base.Channel.Getir(request);
        }
        
        public string Getir(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequestBody();
            inValue.Body.doktorID = doktorID;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).Getir(inValue);
            return retVal.Body.GetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap.GetirAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest request) {
            return base.Channel.GetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirResponse> GetirAsync(int doktorID) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.GetirRequestBody();
            inValue.Body.doktorID = doktorID;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceMesai.WebServiceMesaiSoap)(this)).GetirAsync(inValue);
        }
        
        public int Kontrol(int doktorID) {
            return base.Channel.Kontrol(doktorID);
        }
        
        public System.Threading.Tasks.Task<int> KontrolAsync(int doktorID) {
            return base.Channel.KontrolAsync(doktorID);
        }
        
        public void Sil(int doktorID) {
            base.Channel.Sil(doktorID);
        }
        
        public System.Threading.Tasks.Task SilAsync(int doktorID) {
            return base.Channel.SilAsync(doktorID);
        }
    }
}
