//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceListele.WebServiceListeleSoap")]
    public interface WebServiceListeleSoap {
        
        // CODEGEN: Generating message contract since element name ListeleDoktorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListeleDoktor", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse ListeleDoktor(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListeleDoktor", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse> ListeleDoktorAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListeleDoktorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListeleDoktor", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequestBody Body;
        
        public ListeleDoktorRequest() {
        }
        
        public ListeleDoktorRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListeleDoktorRequestBody {
        
        public ListeleDoktorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListeleDoktorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListeleDoktorResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponseBody Body;
        
        public ListeleDoktorResponse() {
        }
        
        public ListeleDoktorResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListeleDoktorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListeleDoktorResult;
        
        public ListeleDoktorResponseBody() {
        }
        
        public ListeleDoktorResponseBody(string ListeleDoktorResult) {
            this.ListeleDoktorResult = ListeleDoktorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceListeleSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceListeleSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap {
        
        public WebServiceListeleSoapClient() {
        }
        
        public WebServiceListeleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceListeleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceListeleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceListeleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap.ListeleDoktor(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest request) {
            return base.Channel.ListeleDoktor(request);
        }
        
        public string ListeleDoktor() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap)(this)).ListeleDoktor(inValue);
            return retVal.Body.ListeleDoktorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap.ListeleDoktorAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest request) {
            return base.Channel.ListeleDoktorAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorResponse> ListeleDoktorAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.ListeleDoktorRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceListele.WebServiceListeleSoap)(this)).ListeleDoktorAsync(inValue);
        }
    }
}
