//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoktor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDoktor.WebServiceDoktorSoap")]
    public interface WebServiceDoktorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        bool Ekle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EkleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        bool Guncelle(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GuncelleAsync(int doktorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        bool Kontrol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> KontrolAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDoktorSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoktor.WebServiceDoktorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDoktorSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceDoktor.WebServiceDoktorSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceDoktor.WebServiceDoktorSoap {
        
        public WebServiceDoktorSoapClient() {
        }
        
        public WebServiceDoktorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDoktorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDoktorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDoktorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ekle() {
            return base.Channel.Ekle();
        }
        
        public System.Threading.Tasks.Task<bool> EkleAsync() {
            return base.Channel.EkleAsync();
        }
        
        public bool Guncelle(int doktorID) {
            return base.Channel.Guncelle(doktorID);
        }
        
        public System.Threading.Tasks.Task<bool> GuncelleAsync(int doktorID) {
            return base.Channel.GuncelleAsync(doktorID);
        }
        
        public bool Kontrol() {
            return base.Channel.Kontrol();
        }
        
        public System.Threading.Tasks.Task<bool> KontrolAsync() {
            return base.Channel.KontrolAsync();
        }
    }
}
