//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGiris.WebServiceGirisSoap")]
    public interface WebServiceGirisSoap {
        
        // CODEGEN: Generating message contract since element name UyeGirisYapResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UyeGirisYap", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse UyeGirisYap(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UyeGirisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse> UyeGirisYapAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest request);
        
        // CODEGEN: Generating message contract since element name DoktorGirisYapResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoktorGirisYap", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse DoktorGirisYap(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoktorGirisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse> DoktorGirisYapAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UyeGirisYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UyeGirisYap", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequestBody Body;
        
        public UyeGirisYapRequest() {
        }
        
        public UyeGirisYapRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UyeGirisYapRequestBody {
        
        public UyeGirisYapRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UyeGirisYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UyeGirisYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponseBody Body;
        
        public UyeGirisYapResponse() {
        }
        
        public UyeGirisYapResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UyeGirisYapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UyeGirisYapResult;
        
        public UyeGirisYapResponseBody() {
        }
        
        public UyeGirisYapResponseBody(string UyeGirisYapResult) {
            this.UyeGirisYapResult = UyeGirisYapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoktorGirisYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoktorGirisYap", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequestBody Body;
        
        public DoktorGirisYapRequest() {
        }
        
        public DoktorGirisYapRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DoktorGirisYapRequestBody {
        
        public DoktorGirisYapRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoktorGirisYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoktorGirisYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponseBody Body;
        
        public DoktorGirisYapResponse() {
        }
        
        public DoktorGirisYapResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoktorGirisYapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoktorGirisYapResult;
        
        public DoktorGirisYapResponseBody() {
        }
        
        public DoktorGirisYapResponseBody(string DoktorGirisYapResult) {
            this.DoktorGirisYapResult = DoktorGirisYapResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceGirisSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceGirisSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap {
        
        public WebServiceGirisSoapClient() {
        }
        
        public WebServiceGirisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceGirisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGirisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGirisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap.UyeGirisYap(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest request) {
            return base.Channel.UyeGirisYap(request);
        }
        
        public string UyeGirisYap() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap)(this)).UyeGirisYap(inValue);
            return retVal.Body.UyeGirisYapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap.UyeGirisYapAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest request) {
            return base.Channel.UyeGirisYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapResponse> UyeGirisYapAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.UyeGirisYapRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap)(this)).UyeGirisYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap.DoktorGirisYap(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest request) {
            return base.Channel.DoktorGirisYap(request);
        }
        
        public string DoktorGirisYap() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap)(this)).DoktorGirisYap(inValue);
            return retVal.Body.DoktorGirisYapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap.DoktorGirisYapAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest request) {
            return base.Channel.DoktorGirisYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapResponse> DoktorGirisYapAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.DoktorGirisYapRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceGiris.WebServiceGirisSoap)(this)).DoktorGirisYapAsync(inValue);
        }
    }
}
