//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRandevu.WebServiceRandevuSoap")]
    public interface WebServiceRandevuSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        void Ekle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task EkleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        void Sil(int randevuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        System.Threading.Tasks.Task SilAsync(int randevuID);
        
        // CODEGEN: Generating message contract since element name KontrolResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse Kontrol(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse> KontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CiftTarih) of message CiftTarih does not match the default value (GetirRandevu)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CiftTarih", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1 GetirRandevu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CiftTarih", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1> GetirRandevuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih request);
        
        // CODEGEN: Generating message contract since the wrapper name (TekTarih) of message TekTarih does not match the default value (GetirRandevuu)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TekTarih", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1 GetirRandevuu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TekTarih", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1> GetirRandevuuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih request);
        
        // CODEGEN: Generating message contract since the wrapper name (Varsayilan) of message Varsayilan does not match the default value (GetirRandevuuu)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Varsayilan", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1 GetirRandevuuu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Varsayilan", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1> GetirRandevuuuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan request);
        
        // CODEGEN: Generating message contract since element name GetirRandevuTarihResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirRandevuTarih", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse GetirRandevuTarih(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirRandevuTarih", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse> GetirRandevuTarihAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest request);
        
        // CODEGEN: Generating message contract since element name GetirDoktorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirDoktor", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse GetirDoktor(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirDoktor", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse> GetirDoktorAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kontrol", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequestBody Body;
        
        public KontrolRequest() {
        }
        
        public KontrolRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KontrolRequestBody {
        
        public KontrolRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponseBody Body;
        
        public KontrolResponse() {
        }
        
        public KontrolResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KontrolResult;
        
        public KontrolResponseBody() {
        }
        
        public KontrolResponseBody(string KontrolResult) {
            this.KontrolResult = KontrolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CiftTarih", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CiftTarih {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int uyeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime tarihBaslangic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime tarihBitis;
        
        public CiftTarih() {
        }
        
        public CiftTarih(int uyeID, System.DateTime tarihBaslangic, System.DateTime tarihBitis) {
            this.uyeID = uyeID;
            this.tarihBaslangic = tarihBaslangic;
            this.tarihBitis = tarihBitis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CiftTarihResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CiftTarih1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CiftTarihResult;
        
        public CiftTarih1() {
        }
        
        public CiftTarih1(string CiftTarihResult) {
            this.CiftTarihResult = CiftTarihResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekTarih", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TekTarih {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int uyeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime tarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool a;
        
        public TekTarih() {
        }
        
        public TekTarih(int uyeID, System.DateTime tarih, bool a) {
            this.uyeID = uyeID;
            this.tarih = tarih;
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekTarihResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TekTarih1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TekTarihResult;
        
        public TekTarih1() {
        }
        
        public TekTarih1(string TekTarihResult) {
            this.TekTarihResult = TekTarihResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Varsayilan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Varsayilan {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime tarih;
        
        public Varsayilan() {
        }
        
        public Varsayilan(System.DateTime tarih) {
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VarsayilanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Varsayilan1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string VarsayilanResult;
        
        public Varsayilan1() {
        }
        
        public Varsayilan1(string VarsayilanResult) {
            this.VarsayilanResult = VarsayilanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirRandevuTarihRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetirRandevuTarih", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequestBody Body;
        
        public GetirRandevuTarihRequest() {
        }
        
        public GetirRandevuTarihRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetirRandevuTarihRequestBody {
        
        public GetirRandevuTarihRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirRandevuTarihResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetirRandevuTarihResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponseBody Body;
        
        public GetirRandevuTarihResponse() {
        }
        
        public GetirRandevuTarihResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetirRandevuTarihResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetirRandevuTarihResult;
        
        public GetirRandevuTarihResponseBody() {
        }
        
        public GetirRandevuTarihResponseBody(string GetirRandevuTarihResult) {
            this.GetirRandevuTarihResult = GetirRandevuTarihResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirDoktorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetirDoktor", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequestBody Body;
        
        public GetirDoktorRequest() {
        }
        
        public GetirDoktorRequest(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetirDoktorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int doktorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime tarih;
        
        public GetirDoktorRequestBody() {
        }
        
        public GetirDoktorRequestBody(int doktorID, System.DateTime tarih) {
            this.doktorID = doktorID;
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetirDoktorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetirDoktorResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponseBody Body;
        
        public GetirDoktorResponse() {
        }
        
        public GetirDoktorResponse(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetirDoktorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetirDoktorResult;
        
        public GetirDoktorResponseBody() {
        }
        
        public GetirDoktorResponseBody(string GetirDoktorResult) {
            this.GetirDoktorResult = GetirDoktorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceRandevuSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceRandevuSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap {
        
        public WebServiceRandevuSoapClient() {
        }
        
        public WebServiceRandevuSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceRandevuSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRandevuSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRandevuSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ekle() {
            base.Channel.Ekle();
        }
        
        public System.Threading.Tasks.Task EkleAsync() {
            return base.Channel.EkleAsync();
        }
        
        public void Sil(int randevuID) {
            base.Channel.Sil(randevuID);
        }
        
        public System.Threading.Tasks.Task SilAsync(int randevuID) {
            return base.Channel.SilAsync(randevuID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.Kontrol(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest request) {
            return base.Channel.Kontrol(request);
        }
        
        public string Kontrol() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).Kontrol(inValue);
            return retVal.Body.KontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.KontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest request) {
            return base.Channel.KontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolResponse> KontrolAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.KontrolRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).KontrolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1 _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih request) {
            return base.Channel.GetirRandevu(request);
        }
        
        public string GetirRandevu(int uyeID, System.DateTime tarihBaslangic, System.DateTime tarihBitis) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih();
            inValue.uyeID = uyeID;
            inValue.tarihBaslangic = tarihBaslangic;
            inValue.tarihBitis = tarihBitis;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1 retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevu(inValue);
            return retVal.CiftTarihResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih request) {
            return base.Channel.GetirRandevuAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih1> GetirRandevuAsync(int uyeID, System.DateTime tarihBaslangic, System.DateTime tarihBitis) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.CiftTarih();
            inValue.uyeID = uyeID;
            inValue.tarihBaslangic = tarihBaslangic;
            inValue.tarihBitis = tarihBitis;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1 _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih request) {
            return base.Channel.GetirRandevuu(request);
        }
        
        public string GetirRandevuu(int uyeID, System.DateTime tarih, bool a) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih();
            inValue.uyeID = uyeID;
            inValue.tarih = tarih;
            inValue.a = a;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1 retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuu(inValue);
            return retVal.TekTarihResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih request) {
            return base.Channel.GetirRandevuuAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih1> GetirRandevuuAsync(int uyeID, System.DateTime tarih, bool a) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.TekTarih();
            inValue.uyeID = uyeID;
            inValue.tarih = tarih;
            inValue.a = a;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1 _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuuu(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan request) {
            return base.Channel.GetirRandevuuu(request);
        }
        
        public string GetirRandevuuu(System.DateTime tarih) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan();
            inValue.tarih = tarih;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1 retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuuu(inValue);
            return retVal.VarsayilanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuuuAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan request) {
            return base.Channel.GetirRandevuuuAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan1> GetirRandevuuuAsync(System.DateTime tarih) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.Varsayilan();
            inValue.tarih = tarih;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuuuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuTarih(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest request) {
            return base.Channel.GetirRandevuTarih(request);
        }
        
        public string GetirRandevuTarih() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuTarih(inValue);
            return retVal.Body.GetirRandevuTarihResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirRandevuTarihAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest request) {
            return base.Channel.GetirRandevuTarihAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihResponse> GetirRandevuTarihAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirRandevuTarihRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirRandevuTarihAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirDoktor(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest request) {
            return base.Channel.GetirDoktor(request);
        }
        
        public string GetirDoktor(int doktorID, System.DateTime tarih) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.tarih = tarih;
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirDoktor(inValue);
            return retVal.Body.GetirDoktorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse> _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap.GetirDoktorAsync(_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest request) {
            return base.Channel.GetirDoktorAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorResponse> GetirDoktorAsync(int doktorID, System.DateTime tarih) {
            _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.GetirDoktorRequestBody();
            inValue.Body.doktorID = doktorID;
            inValue.Body.tarih = tarih;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReferenceRandevu.WebServiceRandevuSoap)(this)).GetirDoktorAsync(inValue);
        }
    }
}
