//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _031_Bootstrap_Hastane_Deneme.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceAdminKontrolSoap")]
    public interface WebServiceAdminKontrolSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse HelloWorld(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse> HelloWorldAsync(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminKontrol", ReplyAction="*")]
        _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse AdminKontrol(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse> AdminKontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminKontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdminKontrol", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequestBody Body;
        
        public AdminKontrolRequest() {
        }
        
        public AdminKontrolRequest(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminKontrolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AdminKontrolRequestBody() {
        }
        
        public AdminKontrolRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminKontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdminKontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponseBody Body;
        
        public AdminKontrolResponse() {
        }
        
        public AdminKontrolResponse(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminKontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdminKontrolResult;
        
        public AdminKontrolResponseBody() {
        }
        
        public AdminKontrolResponseBody(bool AdminKontrolResult) {
            this.AdminKontrolResult = AdminKontrolResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAdminKontrolSoapChannel : _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAdminKontrolSoapClient : System.ServiceModel.ClientBase<_031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap>, _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap {
        
        public WebServiceAdminKontrolSoapClient() {
        }
        
        public WebServiceAdminKontrolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAdminKontrolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAdminKontrolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAdminKontrolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap.HelloWorld(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequestBody();
            _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse> _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap.HelloWorldAsync(_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReference.HelloWorldRequestBody();
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap.AdminKontrol(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest request) {
            return base.Channel.AdminKontrol(request);
        }
        
        public bool AdminKontrol(string username, string password) {
            _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse retVal = ((_031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap)(this)).AdminKontrol(inValue);
            return retVal.Body.AdminKontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse> _031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap.AdminKontrolAsync(_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest request) {
            return base.Channel.AdminKontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<_031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolResponse> AdminKontrolAsync(string username, string password) {
            _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest inValue = new _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequest();
            inValue.Body = new _031_Bootstrap_Hastane_Deneme.ServiceReference.AdminKontrolRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((_031_Bootstrap_Hastane_Deneme.ServiceReference.WebServiceAdminKontrolSoap)(this)).AdminKontrolAsync(inValue);
        }
    }
}
